version: '3.8'

services:
  drupal:
    image: drupal:latest
    ports:
      - "80:80"
    volumes:
      - ./drupal-modules:/var/www/html/modules
      - ./drupal-profiles:/var/www/html/profiles
      - ./drupal-sites:/var/www/html/sites
      - ./drupal-themes:/var/www/html/themes
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupaluser
      MYSQL_PASSWORD: drupalpw
      MYSQL_HOST: mysql
      PHP_MEMORY_LIMIT: 256M
      PHP_MAX_EXECUTION_TIME: 300

  mysql:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupaluser
      MYSQL_PASSWORD: drupalpw